// Ruling P2-R34: the SiteGround artifact is pushed to a public-facing deploy branch, so
// scripts/build-siteground.mjs's build fails outright if the artifact leaks the machine's own
// absolute repo path, home directory, or username. These tests cover the scanning function
// itself (findLeakedPaths) in isolation — a tiny throwaway directory, not a real build — so
// the "does it actually fail the build" guarantee doesn't depend on reproducing a leak in a
// real bundle (which, correctly, doesn't currently leak anything).
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { findLeakedPaths } from "../scripts/build-siteground.mjs";

let dir: string | undefined;

afterEach(() => {
  if (dir) rmSync(dir, { recursive: true, force: true });
  dir = undefined;
});

describe("findLeakedPaths", () => {
  it("flags a file containing a forbidden value, naming the file and which value matched", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-"));
    writeFileSync(join(dir, "stack.js"), "some code // built at /Users/someone/project\n");

    const offenders = findLeakedPaths(dir, [{ label: "repo absolute path", value: "/Users/someone/project" }]);
    expect(offenders).toHaveLength(1);
    expect(offenders[0]!.file).toContain("stack.js");
    expect(offenders[0]!.label).toBe("repo absolute path");
  });

  it("returns no offenders for a directory containing none of the forbidden values", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-clean-"));
    writeFileSync(join(dir, "stack.js"), "clean content with nothing sensitive\n");

    expect(findLeakedPaths(dir, [{ label: "repo absolute path", value: "/Users/someone/project" }])).toEqual([]);
  });

  it("scans nested directories (e.g. migrations/<app>/*.sql, config/tenants/*.json)", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-nested-"));
    mkdirSync(join(dir, "migrations", "core"), { recursive: true });
    writeFileSync(join(dir, "migrations", "core", "0000_init.sql"), "-- generated by /home/ci/build\n");

    const offenders = findLeakedPaths(dir, [{ label: "home directory", value: "/home/ci" }]);
    expect(offenders).toHaveLength(1);
    expect(offenders[0]!.file).toContain("0000_init.sql");
  });

  it("flags every file that contains the value, not just the first", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-multi-"));
    writeFileSync(join(dir, "a.js"), "leak: carol\n");
    writeFileSync(join(dir, "b.js"), "leak: carol\n");
    writeFileSync(join(dir, "c.js"), "nothing here\n");

    const offenders = findLeakedPaths(dir, [{ label: "username", value: "carol" }]);
    expect(offenders.map((o) => o.file.split("/").pop()).sort()).toEqual(["a.js", "b.js"]);
  });

  it("never flags anything for an empty forbidden value (never a false 'everything leaks')", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-empty-"));
    writeFileSync(join(dir, "stack.js"), "anything at all\n");

    expect(findLeakedPaths(dir, [{ label: "unset username", value: "" }])).toEqual([]);
  });

  it("checks multiple forbidden values independently in one pass", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-multi-values-"));
    writeFileSync(join(dir, "stack.js"), "path /Users/carol/repo and home /Users/carol\n");

    const offenders = findLeakedPaths(dir, [
      { label: "repo path", value: "/Users/carol/repo" },
      { label: "home dir", value: "/Users/carol" },
      { label: "username", value: "carol" },
    ]);
    // All three forbidden values are present in the one file -> one offender entry per label.
    expect(offenders).toHaveLength(3);
    expect(offenders.map((o) => o.label).sort()).toEqual(["home dir", "repo path", "username"]);
  });
});
