// Ruling P2-R34: the SiteGround artifact is pushed to a public-facing deploy branch, so
// scripts/build-siteground.mjs's build fails outright if the artifact leaks the machine's own
// absolute repo path, home directory, or username. These tests cover the scanning function
// itself (findLeakedPaths) in isolation — a tiny throwaway directory, not a real build — so
// the "does it actually fail the build" guarantee doesn't depend on reproducing a leak in a
// real bundle (which, correctly, doesn't currently leak anything).
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { assertHubBuilt, copyStaffWebToHub, findLeakedPaths } from "../scripts/build-siteground.mjs";

let dir: string | undefined;

afterEach(() => {
  if (dir) rmSync(dir, { recursive: true, force: true });
  dir = undefined;
});

describe("findLeakedPaths", () => {
  it("flags a file containing a forbidden value, naming the file and which value matched", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-"));
    writeFileSync(join(dir, "stack.js"), "some code // built at /Users/someone/project\n");

    const offenders = findLeakedPaths(dir, [{ label: "repo absolute path", value: "/Users/someone/project" }]);
    expect(offenders).toHaveLength(1);
    expect(offenders[0]!.file).toContain("stack.js");
    expect(offenders[0]!.label).toBe("repo absolute path");
  });

  it("returns no offenders for a directory containing none of the forbidden values", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-clean-"));
    writeFileSync(join(dir, "stack.js"), "clean content with nothing sensitive\n");

    expect(findLeakedPaths(dir, [{ label: "repo absolute path", value: "/Users/someone/project" }])).toEqual([]);
  });

  it("scans nested directories (e.g. migrations/<app>/*.sql, config/tenants/*.json)", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-nested-"));
    mkdirSync(join(dir, "migrations", "core"), { recursive: true });
    writeFileSync(join(dir, "migrations", "core", "0000_init.sql"), "-- generated by /home/ci/build\n");

    const offenders = findLeakedPaths(dir, [{ label: "home directory", value: "/home/ci" }]);
    expect(offenders).toHaveLength(1);
    expect(offenders[0]!.file).toContain("0000_init.sql");
  });

  it("flags every file that contains the value, not just the first", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-multi-"));
    writeFileSync(join(dir, "a.js"), "leak: carol\n");
    writeFileSync(join(dir, "b.js"), "leak: carol\n");
    writeFileSync(join(dir, "c.js"), "nothing here\n");

    const offenders = findLeakedPaths(dir, [{ label: "username", value: "carol" }]);
    expect(offenders.map((o) => o.file.split("/").pop()).sort()).toEqual(["a.js", "b.js"]);
  });

  it("never flags anything for an empty forbidden value (never a false 'everything leaks')", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-empty-"));
    writeFileSync(join(dir, "stack.js"), "anything at all\n");

    expect(findLeakedPaths(dir, [{ label: "unset username", value: "" }])).toEqual([]);
  });

  it("checks multiple forbidden values independently in one pass", () => {
    dir = mkdtempSync(join(tmpdir(), "leak-test-multi-values-"));
    writeFileSync(join(dir, "stack.js"), "path /Users/carol/repo and home /Users/carol\n");

    const offenders = findLeakedPaths(dir, [
      { label: "repo path", value: "/Users/carol/repo" },
      { label: "home dir", value: "/Users/carol" },
      { label: "username", value: "carol" },
    ]);
    // All three forbidden values are present in the one file -> one offender entry per label.
    expect(offenders).toHaveLength(3);
    expect(offenders.map((o) => o.label).sort()).toEqual(["home dir", "repo path", "username"]);
  });
});

// Task 1 (staff-web), fix round 1: build-siteground.mjs's staff-web step had no test at all —
// these exercise the copy + presence-check functions directly (fast, no real esbuild bundle),
// so a regression that stops dist/siteground/hub/index.html from being produced is caught here
// without needing the slow real build (that real build is still run, and still fails loudly on
// the same check, by runBuild itself — see build-siteground.mjs's own assertHubBuilt call).
describe("copyStaffWebToHub / assertHubBuilt", () => {
  let staffWebDistDir: string | undefined;
  let outDir: string | undefined;

  afterEach(() => {
    if (staffWebDistDir) rmSync(staffWebDistDir, { recursive: true, force: true });
    if (outDir) rmSync(outDir, { recursive: true, force: true });
    staffWebDistDir = undefined;
    outDir = undefined;
  });

  it("copies a built staff-web dist to <outDir>/hub, and assertHubBuilt passes against it", () => {
    staffWebDistDir = mkdtempSync(join(tmpdir(), "staff-web-dist-"));
    mkdirSync(join(staffWebDistDir, "assets"), { recursive: true });
    writeFileSync(join(staffWebDistDir, "index.html"), "<!doctype html><body>staff web shell</body>");
    writeFileSync(join(staffWebDistDir, "assets", "app-abc123.js"), "console.log('x');\n");
    const dir = (outDir = mkdtempSync(join(tmpdir(), "siteground-out-")));

    copyStaffWebToHub(staffWebDistDir, dir);

    expect(existsSync(join(dir, "hub", "index.html"))).toBe(true);
    expect(readFileSync(join(dir, "hub", "index.html"), "utf8")).toContain("staff web shell");
    expect(existsSync(join(dir, "hub", "assets", "app-abc123.js"))).toBe(true);
    expect(() => assertHubBuilt(dir)).not.toThrow();
  });

  it("assertHubBuilt throws when dist/siteground/hub/index.html was never produced — this is what would catch the staff-web step silently disappearing from runBuild", () => {
    const dir = (outDir = mkdtempSync(join(tmpdir(), "siteground-out-missing-")));
    // dir exists, but nothing ever copied a hub/ folder into it (the step this guards).
    expect(() => assertHubBuilt(dir)).toThrow(/dist\/siteground\/hub\/index\.html is missing/);
  });

  it("assertHubBuilt throws when hub/ exists but index.html itself is missing from it", () => {
    const dir = (outDir = mkdtempSync(join(tmpdir(), "siteground-out-partial-")));
    mkdirSync(join(dir, "hub", "assets"), { recursive: true });
    writeFileSync(join(dir, "hub", "assets", "app-abc123.js"), "console.log('x');\n");
    expect(() => assertHubBuilt(dir)).toThrow(/index\.html is missing/);
  });
});
