CREATE TABLE "activities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"start_at" timestamp with time zone,
	"end_at" timestamp with time zone,
	"nr_at" timestamp with time zone,
	"potential_dates" text,
	"is_all_day" boolean DEFAULT false NOT NULL,
	"is_confirmed" boolean DEFAULT false NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"details" text DEFAULT '' NOT NULL,
	"schedule" text DEFAULT '' NOT NULL,
	"significance" text DEFAULT '' NOT NULL,
	"strategy" text,
	"comments" text,
	"hq_comments" text,
	"lead_organization" text,
	"venue" text,
	"other_city" text,
	"translations" text[] DEFAULT '{}'::text[] NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"hq_status" text,
	"hq_section" text DEFAULT 'events_and_speeches' NOT NULL,
	"long_term_outlook" boolean DEFAULT false NOT NULL,
	"nr_distribution_id" integer,
	"premier_requested_id" integer,
	"contact_ministry_key" text,
	"government_representative_id" integer,
	"comm_contact_id" integer,
	"event_planner_id" integer,
	"videographer_id" integer,
	"city_id" integer,
	"is_issue" boolean DEFAULT false NOT NULL,
	"is_at_legislature" boolean DEFAULT false NOT NULL,
	"is_confidential" boolean DEFAULT false NOT NULL,
	"is_cross_government" boolean DEFAULT false NOT NULL,
	"is_milestone" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" uuid,
	"needs_review" text[] DEFAULT '{}'::text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"last_updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated_by" uuid,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "activities_status_check" CHECK ("activities"."status" IN ('new','changed','reviewed')),
	CONSTRAINT "activities_hq_status_check" CHECK ("activities"."hq_status" IS NULL OR "activities"."hq_status" IN ('new','changed')),
	CONSTRAINT "activities_hq_section_check" CHECK ("activities"."hq_section" IN ('issues_and_reports','events_and_speeches','in_the_news','not_on_la')),
	CONSTRAINT "activities_needs_review_check" CHECK ("activities"."needs_review" <@ ARRAY['title','details','representative','city','start_date','end_date','categories','comm_materials','active','significance','strategy','scheduling_considerations','internal_notes','lead_organization','initiatives','tags','origin','distribution','translations_required','premier_requested','venue','event_planner','digital']::text[]),
	CONSTRAINT "activities_title_length" CHECK (char_length("activities"."title") <= 500),
	CONSTRAINT "activities_details_length" CHECK (char_length("activities"."details") <= 700),
	CONSTRAINT "activities_schedule_length" CHECK (char_length("activities"."schedule") <= 500),
	CONSTRAINT "activities_significance_length" CHECK (char_length("activities"."significance") <= 500),
	CONSTRAINT "activities_strategy_length" CHECK (char_length("activities"."strategy") <= 500),
	CONSTRAINT "activities_comments_length" CHECK (char_length("activities"."comments") <= 4000),
	CONSTRAINT "activities_hq_comments_length" CHECK (char_length("activities"."hq_comments") <= 2000),
	CONSTRAINT "activities_lead_organization_length" CHECK (char_length("activities"."lead_organization") <= 100),
	CONSTRAINT "activities_venue_length" CHECK (char_length("activities"."venue") <= 150),
	CONSTRAINT "activities_other_city_length" CHECK (char_length("activities"."other_city") <= 150),
	CONSTRAINT "activities_potential_dates_length" CHECK (char_length("activities"."potential_dates") <= 70)
);
--> statement-breakpoint
CREATE TABLE "activity_categories" (
	"activity_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	CONSTRAINT "activity_categories_activity_id_category_id_pk" PRIMARY KEY("activity_id","category_id")
);
--> statement-breakpoint
CREATE TABLE "activity_change_fields" (
	"change_id" integer NOT NULL,
	"field_key" text NOT NULL,
	"old_value" text,
	"new_value" text,
	CONSTRAINT "activity_change_fields_change_id_field_key_pk" PRIMARY KEY("change_id","field_key")
);
--> statement-breakpoint
CREATE TABLE "activity_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activity_id" integer NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_id" uuid,
	"actor_name" text NOT NULL,
	"action" text NOT NULL,
	"source" text DEFAULT 'calendar' NOT NULL,
	"contact_ministry_key" text,
	CONSTRAINT "activity_changes_action_check" CHECK ("activity_changes"."action" IN ('created','updated','cloned','reviewed','deleted','transferred','la_status_cleared')),
	CONSTRAINT "activity_changes_source_check" CHECK ("activity_changes"."source" IN ('calendar','legacy_log'))
);
--> statement-breakpoint
CREATE TABLE "activity_comm_materials" (
	"activity_id" integer NOT NULL,
	"comm_material_id" integer NOT NULL,
	CONSTRAINT "activity_comm_materials_activity_id_comm_material_id_pk" PRIMARY KEY("activity_id","comm_material_id")
);
--> statement-breakpoint
CREATE TABLE "activity_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activity_id" integer NOT NULL,
	"file_name" text NOT NULL,
	"content_type" text NOT NULL,
	"length" integer NOT NULL,
	"sha256" text NOT NULL,
	"storage_key" text NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"uploaded_by" uuid
);
--> statement-breakpoint
CREATE TABLE "activity_initiatives" (
	"activity_id" integer NOT NULL,
	"initiative_id" integer NOT NULL,
	CONSTRAINT "activity_initiatives_activity_id_initiative_id_pk" PRIMARY KEY("activity_id","initiative_id")
);
--> statement-breakpoint
CREATE TABLE "activity_keywords" (
	"activity_id" integer NOT NULL,
	"keyword_id" integer NOT NULL,
	CONSTRAINT "activity_keywords_activity_id_keyword_id_pk" PRIMARY KEY("activity_id","keyword_id")
);
--> statement-breakpoint
CREATE TABLE "activity_locks" (
	"activity_id" integer PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"tab_id" text NOT NULL,
	"acquired_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_active_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activity_nr_origins" (
	"activity_id" integer NOT NULL,
	"nr_origin_id" integer NOT NULL,
	CONSTRAINT "activity_nr_origins_activity_id_nr_origin_id_pk" PRIMARY KEY("activity_id","nr_origin_id")
);
--> statement-breakpoint
CREATE TABLE "activity_sectors" (
	"activity_id" integer NOT NULL,
	"term_key" text NOT NULL,
	CONSTRAINT "activity_sectors_activity_id_term_key_pk" PRIMARY KEY("activity_id","term_key")
);
--> statement-breakpoint
CREATE TABLE "activity_shared_with" (
	"activity_id" integer NOT NULL,
	"ministry_key" text NOT NULL,
	CONSTRAINT "activity_shared_with_activity_id_ministry_key_pk" PRIMARY KEY("activity_id","ministry_key")
);
--> statement-breakpoint
CREATE TABLE "activity_tags" (
	"activity_id" integer NOT NULL,
	"term_key" text NOT NULL,
	CONSTRAINT "activity_tags_activity_id_term_key_pk" PRIMARY KEY("activity_id","term_key")
);
--> statement-breakpoint
CREATE TABLE "activity_themes" (
	"activity_id" integer NOT NULL,
	"term_key" text NOT NULL,
	CONSTRAINT "activity_themes_activity_id_term_key_pk" PRIMARY KEY("activity_id","term_key")
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comm_contacts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comm_contacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"ministry_key" text NOT NULL,
	"rank" integer,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "comm_contacts_rank_check" CHECK ("comm_contacts"."rank" IS NULL OR "comm_contacts"."rank" BETWEEN 1 AND 6)
);
--> statement-breakpoint
CREATE TABLE "comm_materials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comm_materials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event_planners" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_planners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"phone" text,
	"job_title" text
);
--> statement-breakpoint
CREATE TABLE "favourites" (
	"user_id" uuid NOT NULL,
	"activity_id" integer NOT NULL,
	CONSTRAINT "favourites_user_id_activity_id_pk" PRIMARY KEY("user_id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "government_representatives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "government_representatives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "initiatives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "initiatives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"short_name" text
);
--> statement-breakpoint
CREATE TABLE "keywords" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "keywords_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_distributions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nr_distributions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_origins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nr_origins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orgs" (
	"key" text PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"abbreviation" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean NOT NULL,
	"is_hq" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "premier_requested" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "premier_requested_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "release_links" (
	"release_id" uuid PRIMARY KEY NOT NULL,
	"activity_id" integer NOT NULL,
	"key" text,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"publish_at" timestamp with time zone,
	"released_at" timestamp with time zone,
	"reference" text,
	"headline" text,
	"last_sequence" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saved_filters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saved_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_id" uuid NOT NULL,
	"name" text NOT NULL,
	"filter" jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "saved_filters_name_length" CHECK (char_length("saved_filters"."name") <= 200)
);
--> statement-breakpoint
CREATE TABLE "terms" (
	"kind" text NOT NULL,
	"key" text NOT NULL,
	"display_name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean NOT NULL,
	CONSTRAINT "terms_kind_key_pk" PRIMARY KEY("kind","key"),
	CONSTRAINT "terms_kind_check" CHECK ("terms"."kind" IN ('sector','theme','tag'))
);
--> statement-breakpoint
CREATE TABLE "user_profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"phone" text,
	"mobile" text,
	"job_title" text,
	"description" text,
	"list_display" text,
	"hidden_columns" text[] DEFAULT '{}'::text[] NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_profiles_phone_check" CHECK ("user_profiles"."phone" IS NULL OR "user_profiles"."phone" ~ '^[0-9-]{12}$'),
	CONSTRAINT "user_profiles_mobile_check" CHECK ("user_profiles"."mobile" IS NULL OR "user_profiles"."mobile" ~ '^[0-9-]{12}$'),
	CONSTRAINT "user_profiles_list_display_check" CHECK ("user_profiles"."list_display" IS NULL OR "user_profiles"."list_display" IN ('all','my_ministries','my_activities','my_watchlist')),
	CONSTRAINT "user_profiles_job_title_length" CHECK (char_length("user_profiles"."job_title") <= 100),
	CONSTRAINT "user_profiles_description_length" CHECK (char_length("user_profiles"."description") <= 2000)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text,
	"display_name" text NOT NULL,
	"is_active" boolean NOT NULL,
	"calendar_role" text,
	"organization_keys" text[] DEFAULT '{}'::text[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "videographers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "videographers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"job_title" text
);
--> statement-breakpoint
CREATE TABLE "aggregate_sequences" (
	"aggregate_id" text PRIMARY KEY NOT NULL,
	"last_sequence" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inbox_events" (
	"event_id" uuid PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"type" text NOT NULL,
	"outcome" text NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inbox_positions" (
	"source" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"last_sequence" integer NOT NULL,
	CONSTRAINT "inbox_positions_source_aggregate_id_pk" PRIMARY KEY("source","aggregate_id")
);
--> statement-breakpoint
CREATE TABLE "outbox_deliveries" (
	"event_id" uuid NOT NULL,
	"subscriber" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_until" timestamp with time zone,
	"last_error" text,
	"delivered_at" timestamp with time zone,
	CONSTRAINT "outbox_deliveries_event_id_subscriber_pk" PRIMARY KEY("event_id","subscriber")
);
--> statement-breakpoint
CREATE TABLE "outbox_events" (
	"id" uuid PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"sequence" integer NOT NULL,
	"envelope" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_nr_distribution_id_nr_distributions_id_fk" FOREIGN KEY ("nr_distribution_id") REFERENCES "public"."nr_distributions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_premier_requested_id_premier_requested_id_fk" FOREIGN KEY ("premier_requested_id") REFERENCES "public"."premier_requested"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_government_representative_id_government_representatives_id_fk" FOREIGN KEY ("government_representative_id") REFERENCES "public"."government_representatives"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_comm_contact_id_comm_contacts_id_fk" FOREIGN KEY ("comm_contact_id") REFERENCES "public"."comm_contacts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_event_planner_id_event_planners_id_fk" FOREIGN KEY ("event_planner_id") REFERENCES "public"."event_planners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_videographer_id_videographers_id_fk" FOREIGN KEY ("videographer_id") REFERENCES "public"."videographers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_categories" ADD CONSTRAINT "activity_categories_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_categories" ADD CONSTRAINT "activity_categories_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_change_fields" ADD CONSTRAINT "activity_change_fields_change_id_activity_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "public"."activity_changes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_changes" ADD CONSTRAINT "activity_changes_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_comm_materials" ADD CONSTRAINT "activity_comm_materials_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_comm_materials" ADD CONSTRAINT "activity_comm_materials_comm_material_id_comm_materials_id_fk" FOREIGN KEY ("comm_material_id") REFERENCES "public"."comm_materials"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_files" ADD CONSTRAINT "activity_files_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_initiatives" ADD CONSTRAINT "activity_initiatives_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_initiatives" ADD CONSTRAINT "activity_initiatives_initiative_id_initiatives_id_fk" FOREIGN KEY ("initiative_id") REFERENCES "public"."initiatives"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_keywords" ADD CONSTRAINT "activity_keywords_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_keywords" ADD CONSTRAINT "activity_keywords_keyword_id_keywords_id_fk" FOREIGN KEY ("keyword_id") REFERENCES "public"."keywords"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_locks" ADD CONSTRAINT "activity_locks_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_nr_origins" ADD CONSTRAINT "activity_nr_origins_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_nr_origins" ADD CONSTRAINT "activity_nr_origins_nr_origin_id_nr_origins_id_fk" FOREIGN KEY ("nr_origin_id") REFERENCES "public"."nr_origins"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_sectors" ADD CONSTRAINT "activity_sectors_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_shared_with" ADD CONSTRAINT "activity_shared_with_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_tags" ADD CONSTRAINT "activity_tags_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_themes" ADD CONSTRAINT "activity_themes_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favourites" ADD CONSTRAINT "favourites_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "release_links" ADD CONSTRAINT "release_links_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outbox_deliveries" ADD CONSTRAINT "outbox_deliveries_event_id_outbox_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."outbox_events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activities_start_at_idx" ON "activities" USING btree ("start_at");--> statement-breakpoint
CREATE INDEX "activities_end_at_idx" ON "activities" USING btree ("end_at");--> statement-breakpoint
CREATE INDEX "activities_contact_ministry_idx" ON "activities" USING btree ("contact_ministry_key");--> statement-breakpoint
CREATE INDEX "activities_comm_contact_idx" ON "activities" USING btree ("comm_contact_id");--> statement-breakpoint
CREATE INDEX "activity_changes_activity_at_idx" ON "activity_changes" USING btree ("activity_id","at");--> statement-breakpoint
CREATE INDEX "activity_changes_at_idx" ON "activity_changes" USING btree ("at");--> statement-breakpoint
CREATE UNIQUE INDEX "activity_files_name_idx" ON "activity_files" USING btree ("activity_id","file_name");--> statement-breakpoint
CREATE INDEX "activity_shared_with_ministry_idx" ON "activity_shared_with" USING btree ("ministry_key");--> statement-breakpoint
CREATE UNIQUE INDEX "comm_contacts_user_ministry_idx" ON "comm_contacts" USING btree ("user_id","ministry_key");--> statement-breakpoint
CREATE INDEX "favourites_activity_idx" ON "favourites" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "release_links_activity_idx" ON "release_links" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "saved_filters_owner_idx" ON "saved_filters" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "outbox_deliveries_due_idx" ON "outbox_deliveries" USING btree ("status","next_attempt_at");