import type { ReleaseRecord } from "./catalogue";

export const sampleRelease: ReleaseRecord = {
  key: "2026TT0103-001121",
  kind: "releases",
  reference: "NEWS-34336",
  atomId: "uuid:9af8cc16-0ae5-4ec6-ad58-fdb081d44e37",
  publishDate: "2026-10-01T15:10:00-07:00",
  leadMinistryKey: "transportation-and-transit",
  summary: "Drivers can expect major traffic-pattern changes on Highway 11.",
  socialMediaSummary: null,
  socialMediaHeadline: null,
  keywords: "",
  location: "Abbotsford",
  hasMediaAssets: false,
  hasTranslations: false,
  isNewsOnDemand: true,
  assetUrl: "",
  redirectUri: null,
  documents: [
    {
      pageTitle: "Traffic Advisory",
      languageId: 4105,
      headline: "Traffic-pattern change planned for Highway 11 at Highway 1",
      subheadline: "",
      detailsHtml: "<p>Drivers can expect…</p>",
      byline: "",
      contacts: [{ title: "Ministry of Transportation and Transit", details: "Media Relations\n250-555-0101" }],
    },
  ],
  ministryKeys: ["transportation-and-transit"],
  sectorKeys: ["government-operations", "services"],
  tagKeys: [],
  themeKeys: [],
  assets: null,
  translations: null,
  publishFlags: { toWeb: true, toSubscribers: true, toMediaLists: false },
  mediaListKeys: [],
  renditions: null,
  timestamp: "2026-10-01T15:10:28.0375661-07:00",
  mediaText: null,
};
