#!/usr/bin/env -S node --
// Task 15: generates the KEY=value env vars to paste into SiteGround's Site Tools > Devs >
// Environment Variables for the apps/stack artifact (see docs/deploy/siteground.md).
//
// Interactive (default): prompts for everything needed (domain, the NoD manage-page URL, the
// admin username/password, the database user/password/names, and SMTP), hiding the admin and
// database/SMTP passwords the same way `npm run auth:hash-password` hides its password (never
// echoed to the terminal) — see packages/auth/src/cli/hidden-input.ts, reused here rather than
// reimplemented.
//
// Non-interactive (`--non-interactive`, or auto-detected when stdin isn't a TTY): reads every
// value from SITEGROUND_* env vars instead of prompting — for tests and scripted/CI use. The
// admin and database/SMTP passwords are then necessarily plain env vars (there is no terminal
// to hide them from); this mode is documented as "for tests", not for a human typing a real
// production password into a shell history.
//
// Every secret the stack needs purely for its own internal wiring (TICK_TOKEN,
// LOCAL_AUTH_SECRET, and the four inter-app event-delivery HMAC secrets) is always generated
// fresh with crypto.randomBytes — never prompted for, never read from an env var — since
// nothing outside this one run needs to know them in advance.
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline/promises";
import { pathToFileURL } from "node:url";
import { hashPassword } from "../packages/auth/src/password";
import { applyKeypress, INITIAL_KEYPRESS_STATE, type KeypressState } from "../packages/auth/src/cli/hidden-input";

export interface SiteGroundEnvInput {
  domain: string;
  manageUrl: string;
  adminUsername: string;
  /** Already hashed (output of hashPassword) — the CLI hashes the raw password itself; tests
   * that want a deterministic, pre-hashed value pass one in directly. */
  adminPasswordHash: string;
  dbUser: string;
  dbPassword: string;
  dbNames: { core: string; nrms: string; newsApi: string; site: string; nod: string; distribution: string };
  smtp: { host: string; port: number; secure: boolean; user?: string; pass?: string };
  mailFrom: string;
  mailRedirectTo: string[];
  internalDomains?: string[];
}

export interface GeneratedSecrets {
  localAuthSecret: string;
  tickToken: string;
  stackEventSecret: string;
}

/** `>= 32 chars` (the same bar LOCAL_AUTH_SECRET/TICK_TOKEN enforce at startup — see
 * apps/stack/src/env.ts) — 32 random bytes as hex is 64 characters, comfortably over it. */
export function generateSecret(): string {
  return randomBytes(32).toString("hex");
}

export function generateSecrets(): GeneratedSecrets {
  return {
    localAuthSecret: generateSecret(),
    tickToken: generateSecret(),
    stackEventSecret: generateSecret(),
  };
}

function dbUrl(user: string, password: string, name: string): string {
  // DATABASE_URL must NEVER be self:/... (ruling P2-R32 — apps/stack/src/env.ts excludes it
  // from self: resolution anyway, but the generator shouldn't even tempt it) — always a real
  // postgres:// URL at localhost, per siteground-facts.md (the public hostname is rejected).
  return `postgres://${encodeURIComponent(user)}:${encodeURIComponent(password)}@localhost:5432/${name}`;
}

/**
 * Builds every KEY=value line for the stack's six apps, wiring the fixed internal event graph
 * (core -> news-api, nrms -> news-api + nod, news-api -> public-site — see
 * apps/stack/src/stack.test.ts's setupStack, the real wiring this mirrors) with freshly
 * generated secrets, and the operator-supplied domain/credentials everywhere else. Pure and
 * synchronous — no I/O, no randomness of its own — so it's fully unit-testable without a TTY,
 * a database, or mocking crypto.
 */
export function buildEnvLines(input: SiteGroundEnvInput, secrets: GeneratedSecrets): string[] {
  const publicSiteUrl = `https://${input.domain}/site`;
  const lines: string[] = [
    "# Generated by scripts/siteground-env.ts -- paste into SiteGround Site Tools > Devs > Environment Variables.",
    "# PORT is injected by SiteGround itself -- do not set it here.",
    "# TENANT_CONFIG is left unset -- the artifact's own config/tenants/bc.json next to stack.js is used.",
    "",
    "NODE_ENV=production",
    "STACK_LOOPS=false",
    "UPDATES_HUB_ENABLED=false",
    `TICK_TOKEN=${secrets.tickToken}`,
    "",
    "LOCAL_ADMIN_ENABLED=true",
    "LOCAL_ADMIN_ALLOW_IN_PRODUCTION=true",
    `LOCAL_ADMIN_USERNAME=${input.adminUsername}`,
    `LOCAL_ADMIN_PASSWORD_HASH=${input.adminPasswordHash}`,
    `LOCAL_AUTH_SECRET=${secrets.localAuthSecret}`,
    // All internal event wiring (who sends which events to whom, and the per-pair signing
    // secrets) is derived by the stack from this one value — see apps/stack/src/env.ts.
    `STACK_EVENT_SECRET=${secrets.stackEventSecret}`,
    "",
    `CORE_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.core)}`,
    "",
    `NRMS_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.nrms)}`,
    "",
    `NEWSAPI_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.newsApi)}`,
    "",
    `SITE_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.site)}`,
    "SITE_NEWS_API_URL=self:/",
    "SITE_OUTPUT_DIR=./site-output",
    `SITE_PUBLIC_SITE_URL=${publicSiteUrl}`,
    "",
    `NOD_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.nod)}`,
    "NOD_DISTRIBUTION_URL=self:/distribution",
    `NOD_PUBLIC_SITE_URL=${publicSiteUrl}`,
    `NOD_MANAGE_URL=${input.manageUrl}`,
    "",
    `DIST_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.distribution)}`,
    `DIST_SMTP_HOST=${input.smtp.host}`,
    `DIST_SMTP_PORT=${input.smtp.port}`,
    `DIST_SMTP_SECURE=${input.smtp.secure}`,
    ...(input.smtp.user ? [`DIST_SMTP_USER=${input.smtp.user}`] : []),
    ...(input.smtp.pass ? [`DIST_SMTP_PASS=${input.smtp.pass}`] : []),
    `DIST_MAIL_FROM=${input.mailFrom}`,
    `DIST_MAIL_REDIRECT_TO=${input.mailRedirectTo.join(",")}`,
    ...(input.internalDomains?.length ? [`DIST_INTERNAL_DOMAINS=${input.internalDomains.join(",")}`] : []),
  ];
  return lines;
}

const REQUIRED_NON_INTERACTIVE_VARS = [
  "SITEGROUND_DOMAIN",
  "SITEGROUND_MANAGE_URL",
  "SITEGROUND_ADMIN_PASSWORD",
  "SITEGROUND_DB_USER",
  "SITEGROUND_DB_PASSWORD",
  "SITEGROUND_SMTP_HOST",
  "SITEGROUND_MAIL_FROM",
  "SITEGROUND_MAIL_REDIRECT_TO",
] as const;

function commaList(value: string | undefined): string[] {
  return (value ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Reads every value non-interactively from SITEGROUND_* env vars (for tests/CI — see the
 * module doc comment). Returns the admin password's *hash*, not the raw password: the raw
 * `SITEGROUND_ADMIN_PASSWORD` is hashed here with the same `hashPassword` the interactive path
 * uses, so both paths produce an equally valid `LOCAL_ADMIN_PASSWORD_HASH` and neither leaks
 * the raw password into the generated output.
 *
 * Throws, naming every missing var at once (not just the first), if any required one is
 * absent — a partial non-interactive run should fail loudly, not silently fall back to
 * prompting (there's no TTY to prompt on in the cases this mode is for).
 */
export async function collectNonInteractiveInput(env: NodeJS.ProcessEnv): Promise<SiteGroundEnvInput> {
  const missing = REQUIRED_NON_INTERACTIVE_VARS.filter((key) => !env[key]);
  if (missing.length > 0) {
    throw new Error(`--non-interactive is missing required env vars: ${missing.join(", ")}`);
  }
  // Ruling P2-R34: the same >= 12 character rule the interactive prompt enforces (below) —
  // the missing-vars check above already rejects an EMPTY SITEGROUND_ADMIN_PASSWORD (an
  // empty string is falsy), but a short-but-non-empty one would otherwise sail through
  // non-interactive mode and produce a hash for a password nobody should be allowed to set.
  const adminPassword = env.SITEGROUND_ADMIN_PASSWORD!;
  if (adminPassword.length < 12) {
    throw new Error("SITEGROUND_ADMIN_PASSWORD must be at least 12 characters.");
  }
  const dbPrefix = env.SITEGROUND_DB_PREFIX ?? "gcpe";
  return {
    domain: env.SITEGROUND_DOMAIN!,
    manageUrl: env.SITEGROUND_MANAGE_URL!,
    adminUsername: env.SITEGROUND_ADMIN_USERNAME ?? "admin",
    adminPasswordHash: await hashPassword(adminPassword),
    dbUser: env.SITEGROUND_DB_USER!,
    dbPassword: env.SITEGROUND_DB_PASSWORD!,
    dbNames: {
      core: env.SITEGROUND_DB_NAME_CORE ?? `${dbPrefix}_core`,
      nrms: env.SITEGROUND_DB_NAME_NRMS ?? `${dbPrefix}_nrms`,
      newsApi: env.SITEGROUND_DB_NAME_NEWSAPI ?? `${dbPrefix}_news_api`,
      site: env.SITEGROUND_DB_NAME_SITE ?? `${dbPrefix}_site`,
      nod: env.SITEGROUND_DB_NAME_NOD ?? `${dbPrefix}_nod`,
      distribution: env.SITEGROUND_DB_NAME_DIST ?? `${dbPrefix}_distribution`,
    },
    smtp: {
      host: env.SITEGROUND_SMTP_HOST!,
      port: Number(env.SITEGROUND_SMTP_PORT ?? "587"),
      secure: env.SITEGROUND_SMTP_SECURE === "true",
      user: env.SITEGROUND_SMTP_USER,
      pass: env.SITEGROUND_SMTP_PASS,
    },
    mailFrom: env.SITEGROUND_MAIL_FROM!,
    mailRedirectTo: commaList(env.SITEGROUND_MAIL_REDIRECT_TO),
    internalDomains: commaList(env.SITEGROUND_INTERNAL_DOMAINS),
  };
}

// --- Interactive prompting (not exercised by tests: no TTY in CI) ---------------------------

async function readHiddenFromTTY(label: string, stdin: NodeJS.ReadStream & { fd: 0 }): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    let state: KeypressState = INITIAL_KEYPRESS_STATE;
    const cleanup = () => {
      stdin.setRawMode(false);
      stdin.pause();
      stdin.removeListener("data", onData);
      stdin.removeListener("error", onError);
    };
    const onData = (chunk: Buffer) => {
      const result = applyKeypress(state, chunk);
      if (result.action === "submit") {
        cleanup();
        process.stderr.write("\n");
        resolve(result.value);
        return;
      }
      if (result.action === "cancel") {
        cleanup();
        process.stderr.write("\n");
        process.exit(130);
      }
      state = result.state;
    };
    const onError = (err: Error) => {
      cleanup();
      reject(err);
    };
    // Echo off BEFORE the prompt appears: otherwise anything typed or pasted the instant the
    // label shows up is echoed by the still-cooked terminal.
    stdin.setRawMode(true);
    stdin.on("data", onData);
    stdin.on("error", onError);
    stdin.resume();
    process.stderr.write(`${label} (input hidden): `);
  });
}

async function promptHidden(label: string): Promise<string> {
  if (!process.stdin.isTTY) throw new Error(`cannot prompt for "${label}" without a TTY -- use --non-interactive`);
  return readHiddenFromTTY(label, process.stdin as NodeJS.ReadStream & { fd: 0 });
}

/**
 * Plain prompts use readline; hidden prompts read raw bytes from the TTY. The two must never be
 * attached to stdin at the same time: readline would also receive (and could echo) the hidden
 * keystrokes, and the hidden reader pauses stdin when it finishes, which a live readline
 * interface doesn't notice — its next question then waits forever and Node exits silently.
 * So the readline interface is closed before every hidden prompt and recreated after it.
 */
class Prompter {
  private rl: ReturnType<typeof createInterface> | null = null;

  private open(): ReturnType<typeof createInterface> {
    if (!this.rl) {
      this.rl = createInterface({ input: process.stdin, output: process.stderr });
      process.stdin.resume();
    }
    return this.rl;
  }

  close(): void {
    this.rl?.close();
    this.rl = null;
  }

  async plain(label: string, defaultValue?: string): Promise<string> {
    const suffix = defaultValue ? ` [${defaultValue}]` : "";
    const answer = (await this.open().question(`${label}${suffix}: `)).trim();
    if (answer.length > 0) return answer;
    if (defaultValue !== undefined) return defaultValue;
    throw new Error(`"${label}" is required`);
  }

  async hidden(label: string): Promise<string> {
    this.close();
    return promptHidden(label);
  }
}

async function collectInteractiveInput(): Promise<SiteGroundEnvInput> {
  const p = new Prompter();
  try {
    const domain = await p.plain("Public domain (e.g. news.gov.bc.ca)");
    const manageUrl = await p.plain("Subscriber manage/unsubscribe page URL (external)");
    const adminUsername = await p.plain("Admin username", "admin");
    const adminPassword = await p.hidden("Admin password");
    if (adminPassword.length < 12) throw new Error("Admin password must be at least 12 characters.");
    const dbUser = await p.plain("Postgres user (Site Tools-created, shared by all six DBs)");
    const dbPassword = await p.hidden("Postgres password");
    // SiteGround generates database names (e.g. "dbkjyoirx2cq7n") and only lets you set a label, so
    // each app's database name is asked for individually. The prefix only supplies the defaults.
    const dbPrefix = await p.plain("Database name prefix (defaults for the six names below)", "gcpe");
    const dbNames = {
      core: await p.plain("Database name for Core", `${dbPrefix}_core`),
      nrms: await p.plain("Database name for NRMS", `${dbPrefix}_nrms`),
      newsApi: await p.plain("Database name for News API", `${dbPrefix}_news_api`),
      site: await p.plain("Database name for Public Site", `${dbPrefix}_site`),
      nod: await p.plain("Database name for NoD", `${dbPrefix}_nod`),
      distribution: await p.plain("Database name for Distribution", `${dbPrefix}_distribution`),
    };
    const smtpHost = await p.plain("SMTP host (SiteGround mailbox or relay)");
    const smtpPort = Number(await p.plain("SMTP port", "587"));
    const smtpSecure = (await p.plain("SMTP secure (true/false)", "false")) === "true";
    const smtpUser = await p.plain("SMTP username (blank if none)", "");
    const smtpPass = smtpUser ? await p.hidden("SMTP password") : "";
    const mailFrom = await p.plain("Mail From address");
    const mailRedirectTo = commaList(await p.plain("Redirect ALL outgoing mail to (comma-separated test inbox(es))"));
    // Distribution refuses to start without a redirect unless DIST_MAIL_ALLOW_REAL_RECIPIENTS=true,
    // which this test-environment generator deliberately never emits.
    if (mailRedirectTo.length === 0) throw new Error("A redirect address is required for this test environment.");

    return {
      domain,
      manageUrl,
      adminUsername,
      adminPasswordHash: await hashPassword(adminPassword),
      dbUser,
      dbPassword,
      dbNames,
      smtp: { host: smtpHost, port: smtpPort, secure: smtpSecure, user: smtpUser || undefined, pass: smtpPass || undefined },
      mailFrom,
      mailRedirectTo,
    };
  } finally {
    p.close();
  }
}

async function main(): Promise<void> {
  const nonInteractive = process.argv.includes("--non-interactive") || !process.stdin.isTTY;
  const input = nonInteractive ? await collectNonInteractiveInput(process.env) : await collectInteractiveInput();
  const lines = buildEnvLines(input, generateSecrets());
  console.log(lines.join("\n"));
}

// Only run main() when this file is the actual entry point (`node scripts/siteground-env.ts` /
// `tsx scripts/siteground-env.ts`), not when a test imports it for buildEnvLines/generateSecrets/
// collectNonInteractiveInput.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error("[siteground-env]", err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
