#!/usr/bin/env -S node --
// Task 15: generates the KEY=value env vars to paste into SiteGround's Site Tools > Devs >
// Environment Variables for the apps/stack artifact (see docs/deploy/siteground.md).
//
// Interactive (default): prompts for everything needed (domain, the NoD manage-page URL, the
// admin username/password, the database user/password/names, and SMTP), hiding the admin and
// database/SMTP passwords the same way `npm run auth:hash-password` hides its password (never
// echoed to the terminal) — see packages/auth/src/cli/hidden-input.ts, reused here rather than
// reimplemented.
//
// Non-interactive (`--non-interactive`, or auto-detected when stdin isn't a TTY): reads every
// value from SITEGROUND_* env vars instead of prompting — for tests and scripted/CI use. The
// admin and database/SMTP passwords are then necessarily plain env vars (there is no terminal
// to hide them from); this mode is documented as "for tests", not for a human typing a real
// production password into a shell history.
//
// Every secret the stack needs purely for its own internal wiring (TICK_TOKEN,
// LOCAL_AUTH_SECRET, and the four inter-app event-delivery HMAC secrets) is always generated
// fresh with crypto.randomBytes — never prompted for, never read from an env var — since
// nothing outside this one run needs to know them in advance.
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline/promises";
import { pathToFileURL } from "node:url";
import { hashPassword } from "../packages/auth/src/password";
import { applyKeypress, INITIAL_KEYPRESS_STATE, type KeypressState } from "../packages/auth/src/cli/hidden-input";

export interface SiteGroundEnvInput {
  domain: string;
  manageUrl: string;
  adminUsername: string;
  /** Already hashed (output of hashPassword) — the CLI hashes the raw password itself; tests
   * that want a deterministic, pre-hashed value pass one in directly. */
  adminPasswordHash: string;
  dbUser: string;
  dbPassword: string;
  dbNames: { core: string; nrms: string; newsApi: string; site: string; nod: string; distribution: string };
  smtp: { host: string; port: number; secure: boolean; user?: string; pass?: string };
  mailFrom: string;
  mailRedirectTo: string[];
  internalDomains?: string[];
}

export interface GeneratedSecrets {
  localAuthSecret: string;
  tickToken: string;
  coreToNewsApi: string;
  nrmsToNewsApi: string;
  nrmsToNod: string;
  newsApiToSite: string;
}

/** `>= 32 chars` (the same bar LOCAL_AUTH_SECRET/TICK_TOKEN enforce at startup — see
 * apps/stack/src/env.ts) — 32 random bytes as hex is 64 characters, comfortably over it. */
export function generateSecret(): string {
  return randomBytes(32).toString("hex");
}

export function generateSecrets(): GeneratedSecrets {
  return {
    localAuthSecret: generateSecret(),
    tickToken: generateSecret(),
    coreToNewsApi: generateSecret(),
    nrmsToNewsApi: generateSecret(),
    nrmsToNod: generateSecret(),
    newsApiToSite: generateSecret(),
  };
}

function dbUrl(user: string, password: string, name: string): string {
  // DATABASE_URL must NEVER be self:/... (ruling P2-R32 — apps/stack/src/env.ts excludes it
  // from self: resolution anyway, but the generator shouldn't even tempt it) — always a real
  // postgres:// URL at localhost, per siteground-facts.md (the public hostname is rejected).
  return `postgres://${encodeURIComponent(user)}:${encodeURIComponent(password)}@localhost:5432/${name}`;
}

/**
 * Builds every KEY=value line for the stack's six apps, wiring the fixed internal event graph
 * (core -> news-api, nrms -> news-api + nod, news-api -> public-site — see
 * apps/stack/src/stack.test.ts's setupStack, the real wiring this mirrors) with freshly
 * generated secrets, and the operator-supplied domain/credentials everywhere else. Pure and
 * synchronous — no I/O, no randomness of its own — so it's fully unit-testable without a TTY,
 * a database, or mocking crypto.
 */
export function buildEnvLines(input: SiteGroundEnvInput, secrets: GeneratedSecrets): string[] {
  const publicSiteUrl = `https://${input.domain}/site`;
  const lines: string[] = [
    "# Generated by scripts/siteground-env.ts -- paste into SiteGround Site Tools > Devs > Environment Variables.",
    "# PORT is injected by SiteGround itself -- do not set it here.",
    "# TENANT_CONFIG is left unset -- the artifact's own config/tenants/bc.json next to stack.js is used.",
    "",
    "NODE_ENV=production",
    "STACK_LOOPS=false",
    "UPDATES_HUB_ENABLED=false",
    `TICK_TOKEN=${secrets.tickToken}`,
    "",
    "LOCAL_ADMIN_ENABLED=true",
    "LOCAL_ADMIN_ALLOW_IN_PRODUCTION=true",
    `LOCAL_ADMIN_USERNAME=${input.adminUsername}`,
    `LOCAL_ADMIN_PASSWORD_HASH=${input.adminPasswordHash}`,
    `LOCAL_AUTH_SECRET=${secrets.localAuthSecret}`,
    "",
    `CORE_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.core)}`,
    `CORE_EVENT_SUBSCRIBERS=${JSON.stringify([{ name: "news-api", url: "self:/events", secret: secrets.coreToNewsApi, types: ["org.upserted"] }])}`,
    "",
    `NRMS_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.nrms)}`,
    `NRMS_EVENT_SUBSCRIBERS=${JSON.stringify([
      { name: "news-api", url: "self:/events", secret: secrets.nrmsToNewsApi, types: ["release.published"] },
      { name: "nod", url: "self:/nod/events", secret: secrets.nrmsToNod, types: ["release.published"] },
    ])}`,
    "",
    `NEWSAPI_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.newsApi)}`,
    `NEWSAPI_EVENT_SECRETS=${JSON.stringify({ nrms: secrets.nrmsToNewsApi, core: secrets.coreToNewsApi })}`,
    `NEWSAPI_EVENT_SUBSCRIBERS=${JSON.stringify([{ name: "public-site", url: "self:/site-builder/events", secret: secrets.newsApiToSite, types: ["site.rebuild_requested"] }])}`,
    "",
    `SITE_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.site)}`,
    "SITE_NEWS_API_URL=self:/",
    "SITE_OUTPUT_DIR=./site-output",
    `SITE_EVENT_SECRETS=${JSON.stringify({ "news-api": secrets.newsApiToSite })}`,
    `SITE_PUBLIC_SITE_URL=${publicSiteUrl}`,
    "",
    `NOD_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.nod)}`,
    `NOD_EVENT_SECRETS=${JSON.stringify({ nrms: secrets.nrmsToNod })}`,
    "NOD_DISTRIBUTION_URL=self:/distribution",
    `NOD_PUBLIC_SITE_URL=${publicSiteUrl}`,
    `NOD_MANAGE_URL=${input.manageUrl}`,
    "",
    `DIST_DATABASE_URL=${dbUrl(input.dbUser, input.dbPassword, input.dbNames.distribution)}`,
    `DIST_SMTP_HOST=${input.smtp.host}`,
    `DIST_SMTP_PORT=${input.smtp.port}`,
    `DIST_SMTP_SECURE=${input.smtp.secure}`,
    ...(input.smtp.user ? [`DIST_SMTP_USER=${input.smtp.user}`] : []),
    ...(input.smtp.pass ? [`DIST_SMTP_PASS=${input.smtp.pass}`] : []),
    `DIST_MAIL_FROM=${input.mailFrom}`,
    `DIST_MAIL_REDIRECT_TO=${input.mailRedirectTo.join(",")}`,
    ...(input.internalDomains?.length ? [`DIST_INTERNAL_DOMAINS=${input.internalDomains.join(",")}`] : []),
  ];
  return lines;
}

const REQUIRED_NON_INTERACTIVE_VARS = [
  "SITEGROUND_DOMAIN",
  "SITEGROUND_MANAGE_URL",
  "SITEGROUND_ADMIN_PASSWORD",
  "SITEGROUND_DB_USER",
  "SITEGROUND_DB_PASSWORD",
  "SITEGROUND_SMTP_HOST",
  "SITEGROUND_MAIL_FROM",
  "SITEGROUND_MAIL_REDIRECT_TO",
] as const;

function commaList(value: string | undefined): string[] {
  return (value ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Reads every value non-interactively from SITEGROUND_* env vars (for tests/CI — see the
 * module doc comment). Returns the admin password's *hash*, not the raw password: the raw
 * `SITEGROUND_ADMIN_PASSWORD` is hashed here with the same `hashPassword` the interactive path
 * uses, so both paths produce an equally valid `LOCAL_ADMIN_PASSWORD_HASH` and neither leaks
 * the raw password into the generated output.
 *
 * Throws, naming every missing var at once (not just the first), if any required one is
 * absent — a partial non-interactive run should fail loudly, not silently fall back to
 * prompting (there's no TTY to prompt on in the cases this mode is for).
 */
export async function collectNonInteractiveInput(env: NodeJS.ProcessEnv): Promise<SiteGroundEnvInput> {
  const missing = REQUIRED_NON_INTERACTIVE_VARS.filter((key) => !env[key]);
  if (missing.length > 0) {
    throw new Error(`--non-interactive is missing required env vars: ${missing.join(", ")}`);
  }
  const dbPrefix = env.SITEGROUND_DB_PREFIX ?? "gcpe";
  return {
    domain: env.SITEGROUND_DOMAIN!,
    manageUrl: env.SITEGROUND_MANAGE_URL!,
    adminUsername: env.SITEGROUND_ADMIN_USERNAME ?? "admin",
    adminPasswordHash: await hashPassword(env.SITEGROUND_ADMIN_PASSWORD!),
    dbUser: env.SITEGROUND_DB_USER!,
    dbPassword: env.SITEGROUND_DB_PASSWORD!,
    dbNames: {
      core: env.SITEGROUND_DB_NAME_CORE ?? `${dbPrefix}_core`,
      nrms: env.SITEGROUND_DB_NAME_NRMS ?? `${dbPrefix}_nrms`,
      newsApi: env.SITEGROUND_DB_NAME_NEWSAPI ?? `${dbPrefix}_news_api`,
      site: env.SITEGROUND_DB_NAME_SITE ?? `${dbPrefix}_site`,
      nod: env.SITEGROUND_DB_NAME_NOD ?? `${dbPrefix}_nod`,
      distribution: env.SITEGROUND_DB_NAME_DIST ?? `${dbPrefix}_distribution`,
    },
    smtp: {
      host: env.SITEGROUND_SMTP_HOST!,
      port: Number(env.SITEGROUND_SMTP_PORT ?? "587"),
      secure: env.SITEGROUND_SMTP_SECURE === "true",
      user: env.SITEGROUND_SMTP_USER,
      pass: env.SITEGROUND_SMTP_PASS,
    },
    mailFrom: env.SITEGROUND_MAIL_FROM!,
    mailRedirectTo: commaList(env.SITEGROUND_MAIL_REDIRECT_TO),
    internalDomains: commaList(env.SITEGROUND_INTERNAL_DOMAINS),
  };
}

// --- Interactive prompting (not exercised by tests: no TTY in CI) ---------------------------

async function readHiddenFromTTY(label: string, stdin: NodeJS.ReadStream & { fd: 0 }): Promise<string> {
  process.stderr.write(`${label} (input hidden): `);
  return new Promise<string>((resolve, reject) => {
    let state: KeypressState = INITIAL_KEYPRESS_STATE;
    const cleanup = () => {
      stdin.setRawMode(false);
      stdin.pause();
      stdin.removeListener("data", onData);
      stdin.removeListener("error", onError);
    };
    const onData = (chunk: Buffer) => {
      const result = applyKeypress(state, chunk);
      if (result.action === "submit") {
        cleanup();
        process.stderr.write("\n");
        resolve(result.value);
        return;
      }
      if (result.action === "cancel") {
        cleanup();
        process.stderr.write("\n");
        process.exit(130);
      }
      state = result.state;
    };
    const onError = (err: Error) => {
      cleanup();
      reject(err);
    };
    stdin.setRawMode(true);
    stdin.resume();
    stdin.on("data", onData);
    stdin.on("error", onError);
  });
}

async function promptHidden(label: string): Promise<string> {
  if (!process.stdin.isTTY) throw new Error(`cannot prompt for "${label}" without a TTY -- use --non-interactive`);
  return readHiddenFromTTY(label, process.stdin as NodeJS.ReadStream & { fd: 0 });
}

async function promptPlain(rl: ReturnType<typeof createInterface>, label: string, defaultValue?: string): Promise<string> {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = (await rl.question(`${label}${suffix}: `)).trim();
  if (answer.length > 0) return answer;
  if (defaultValue !== undefined) return defaultValue;
  throw new Error(`"${label}" is required`);
}

async function collectInteractiveInput(): Promise<SiteGroundEnvInput> {
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  try {
    const domain = await promptPlain(rl, "Public domain (e.g. news.gov.bc.ca)");
    const manageUrl = await promptPlain(rl, "Subscriber manage/unsubscribe page URL (external)");
    const adminUsername = await promptPlain(rl, "Admin username", "admin");
    const adminPassword = await promptHidden("Admin password");
    if (adminPassword.length < 12) throw new Error("Admin password must be at least 12 characters.");
    const dbUser = await promptPlain(rl, "Postgres user (Site Tools-created, shared by all six DBs)");
    const dbPassword = await promptHidden("Postgres password");
    const dbPrefix = await promptPlain(rl, "Database name prefix", "gcpe");
    const smtpHost = await promptPlain(rl, "SMTP host (SiteGround mailbox or relay)");
    const smtpPort = Number(await promptPlain(rl, "SMTP port", "587"));
    const smtpSecure = (await promptPlain(rl, "SMTP secure (true/false)", "false")) === "true";
    const smtpUser = await promptPlain(rl, "SMTP username (blank if none)", "");
    const smtpPass = smtpUser ? await promptHidden("SMTP password") : "";
    const mailFrom = await promptPlain(rl, "Mail From address");
    const mailRedirectTo = commaList(await promptPlain(rl, "Mail redirect-to address(es), comma-separated (real recipients until this is cleared later)"));

    return {
      domain,
      manageUrl,
      adminUsername,
      adminPasswordHash: await hashPassword(adminPassword),
      dbUser,
      dbPassword,
      dbNames: {
        core: `${dbPrefix}_core`,
        nrms: `${dbPrefix}_nrms`,
        newsApi: `${dbPrefix}_news_api`,
        site: `${dbPrefix}_site`,
        nod: `${dbPrefix}_nod`,
        distribution: `${dbPrefix}_distribution`,
      },
      smtp: { host: smtpHost, port: smtpPort, secure: smtpSecure, user: smtpUser || undefined, pass: smtpPass || undefined },
      mailFrom,
      mailRedirectTo,
    };
  } finally {
    rl.close();
  }
}

async function main(): Promise<void> {
  const nonInteractive = process.argv.includes("--non-interactive") || !process.stdin.isTTY;
  const input = nonInteractive ? await collectNonInteractiveInput(process.env) : await collectInteractiveInput();
  const lines = buildEnvLines(input, generateSecrets());
  console.log(lines.join("\n"));
}

// Only run main() when this file is the actual entry point (`node scripts/siteground-env.ts` /
// `tsx scripts/siteground-env.ts`), not when a test imports it for buildEnvLines/generateSecrets/
// collectNonInteractiveInput.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error("[siteground-env]", err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
